export default [
  { inputs: [{ internalType: 'address', name: 'target', type: 'address' }], name: 'AddressEmptyCode', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'implementation', type: 'address' }],
    name: 'ERC1967InvalidImplementation',
    type: 'error',
  },
  { inputs: [], name: 'ERC1967NonPayable', type: 'error' },
  { inputs: [], name: 'FailedInnerCall', type: 'error' },
  { inputs: [], name: 'InvalidInitialization', type: 'error' },
  { inputs: [], name: 'NotInitializing', type: 'error' },
  { inputs: [{ internalType: 'address', name: 'owner', type: 'address' }], name: 'OwnableInvalidOwner', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'OwnableUnauthorizedAccount',
    type: 'error',
  },
  { inputs: [], name: 'UUPSUnauthorizedCallContext', type: 'error' },
  {
    inputs: [{ internalType: 'bytes32', name: 'slot', type: 'bytes32' }],
    name: 'UUPSUnsupportedProxiableUUID',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint64', name: 'version', type: 'uint64' }],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'implementation', type: 'address' }],
    name: 'Upgraded',
    type: 'event',
  },
  {
    inputs: [],
    name: 'MAX_AUDITOR_NUM',
    outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'UPGRADE_INTERFACE_VERSION',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'bool', name: 'isAgree', type: 'bool' },
      { internalType: 'string', name: 'reason', type: 'string' },
    ],
    name: 'auditDonate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'auditors',
    outputs: [
      {
        components: [
          { internalType: 'string', name: 'idCard', type: 'string' },
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'uint256', name: 'integral', type: 'uint256' },
          { internalType: 'uint16', name: 'age', type: 'uint16' },
          { internalType: 'uint8', name: 'sex', type: 'uint8' },
          { internalType: 'uint256', name: 'cumulativeAmount', type: 'uint256' },
          { internalType: 'uint256[]', name: 'donatedIds', type: 'uint256[]' },
        ],
        internalType: 'struct CharitableDonations.Person[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'auditorsAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'targetAmount', type: 'uint256' },
      { internalType: 'string', name: 'json', type: 'string' },
      { internalType: 'string', name: 'images', type: 'string' },
    ],
    name: 'createDonate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    name: 'donateDetail',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'address', name: 'personAddress', type: 'address' },
          { internalType: 'uint256', name: 'targetAmount', type: 'uint256' },
          { internalType: 'uint256', name: 'currentAmount', type: 'uint256' },
          { internalType: 'string', name: 'images', type: 'string' },
          { internalType: 'string', name: 'json', type: 'string' },
          { internalType: 'bool', name: 'isPassed', type: 'bool' },
          { internalType: 'bool', name: 'isFinish', type: 'bool' },
          { internalType: 'address[]', name: 'auditorsAddress', type: 'address[]' },
          { internalType: 'bool[]', name: 'auditProgress', type: 'bool[]' },
          { internalType: 'string[]', name: 'auditorReason', type: 'string[]' },
        ],
        internalType: 'struct CharitableDonations.Donate',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'donates',
    outputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'address', name: 'personAddress', type: 'address' },
      { internalType: 'uint256', name: 'targetAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'currentAmount', type: 'uint256' },
      { internalType: 'string', name: 'images', type: 'string' },
      { internalType: 'string', name: 'json', type: 'string' },
      { internalType: 'bool', name: 'isPassed', type: 'bool' },
      { internalType: 'bool', name: 'isFinish', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'handleDonate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_usdt', type: 'address' }],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'persons',
    outputs: [
      { internalType: 'string', name: 'idCard', type: 'string' },
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'uint256', name: 'integral', type: 'uint256' },
      { internalType: 'uint16', name: 'age', type: 'uint16' },
      { internalType: 'uint8', name: 'sex', type: 'uint8' },
      { internalType: 'uint256', name: 'cumulativeAmount', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'proxiableUUID',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: 'idCard', type: 'string' },
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'uint16', name: '_age', type: 'uint16' },
      { internalType: 'uint8', name: 'sex', type: 'uint8' },
    ],
    name: 'register',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [{ internalType: 'uint256', name: 'time', type: 'uint256' }],
    name: 'setVoteTime',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_address', type: 'address' }],
    name: 'set_auditor',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_auditorAddress', type: 'address' },
      { internalType: 'string', name: '_reason', type: 'string' },
    ],
    name: 'startVoteAuditor',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'newImplementation', type: 'address' },
      { internalType: 'bytes', name: 'data', type: 'bytes' },
    ],
    name: 'upgradeToAndCall',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'usdt',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_address', type: 'address' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    name: 'userDonateItemAmount',
    outputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_id', type: 'uint256' },
      { internalType: 'bool', name: 'isAgree', type: 'bool' },
      { internalType: 'uint256', name: 'voteNum', type: 'uint256' },
    ],
    name: 'vote',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_id', type: 'uint256' }],
    name: 'voteFinish',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'voteTime',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_address', type: 'address' },
      { internalType: 'uint256', name: 'id', type: 'uint256' },
    ],
    name: 'voterNumDetail',
    outputs: [
      { internalType: 'uint256', name: 'aggreeNum', type: 'uint256' },
      { internalType: 'uint256', name: 'disagreeNum', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_id', type: 'uint256' }],
    name: 'votersDetail',
    outputs: [
      {
        components: [
          {
            components: [
              { internalType: 'string', name: 'idCard', type: 'string' },
              { internalType: 'string', name: 'name', type: 'string' },
              { internalType: 'uint256', name: 'integral', type: 'uint256' },
              { internalType: 'uint16', name: 'age', type: 'uint16' },
              { internalType: 'uint8', name: 'sex', type: 'uint8' },
              { internalType: 'uint256', name: 'cumulativeAmount', type: 'uint256' },
              { internalType: 'uint256[]', name: 'donatedIds', type: 'uint256[]' },
            ],
            internalType: 'struct CharitableDonations.Person',
            name: 'person',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'uint256', name: 'aggreeNum', type: 'uint256' },
              { internalType: 'uint256', name: 'disagreeNum', type: 'uint256' },
            ],
            internalType: 'struct CharitableDonations.VoterNumDetail',
            name: 'voterNumDetail',
            type: 'tuple',
          },
        ],
        internalType: 'struct CharitableDonations.VoterDetail[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'votes',
    outputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'string', name: 'reason', type: 'string' },
      { internalType: 'address', name: 'promoter', type: 'address' },
      { internalType: 'uint256', name: 'startTime', type: 'uint256' },
      { internalType: 'address', name: 'target', type: 'address' },
      { internalType: 'uint256', name: 'agreeNum', type: 'uint256' },
      { internalType: 'uint256', name: 'disagreeNum', type: 'uint256' },
      { internalType: 'bool', name: 'isFinish', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const
